/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#include <stm32f446xx.h>

#include "printf_logger.h"

void FPU_init()
{
	SCB->CPACR |= (0xF << 20);
}

void GPIO_init()
{
	// GPIOA clock enable
	RCC->AHB1ENR |= (1 << 0);

	// PA1 floating input
	GPIOA->PUPDR &= ~(0x3 << 0);
	GPIOA->MODER &= ~(0x3 << 0);

	// PA2 pull-down output
	GPIOA->PUPDR 	= (GPIOA->PUPDR | (0x1 << 3)) & ~(0x1 << 2);
	GPIOA->MODER	= (GPIOA->MODER | (0x1 << 2)) & ~(0x1 << 3);
	GPIOA->OTYPER 	&= ~(0x1 << 0);

}

void print_start()
{
	printf_v("Welcome!\n");
}

int main(void)
{
	FPU_init();
	GPIO_init();
	printf_init();

	print_start();


	bool inState = false;

	while(1)
	{
		for(int i = 0; i < 100000; i++)
		{

		}
		if (inState)
		{
			inState = false;
			printf_v("%d\n", inState);
			GPIOA->ODR &= ~(0x1 << 1);
		}
		else
		{
			inState = true;
			printf_v("%d\n", inState);
			GPIOA->ODR |= (0x1 << 1);
		}
	}

//	for (;;)
//	{
//		if (GPIOA->IDR & 0x1)
//		{
//			if (inState)
//			{
//				inState = false;
//				printf_v("%d\n", inState);
//			}
//
//			GPIOA->ODR &= ~(0x1 << 1);
//		}
//		else
//		{
//			if (!inState)
//			{
//				inState = true;
//				printf_v("%d\n", inState);
//			}
//
//			GPIOA->ODR |= (0x1 << 1);
//		}
//	}


    /* Loop forever */
	for(;;);
}
