/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include <stm32f446xx.h>
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_spi.h"

#include "NES_Defs.h"
#include "NES_Functions.h"
#include "printf_logger.h"

#include "LCDControl.h"
#include "PADControl.h"
#include "RenderEngine.h"
#include "Mario.h"

#define DEFINE_NES_ENGINE
#include "NESEngine.h"


#include "Game.h"



void FPU_init()
{
	SCB->CPACR |= (0xF << 20);
}

volatile uint32_t tim10_t1 = 0;

void Timer_init()
{
	RCC->APB2ENR |= RCC_APB2ENR_TIM10EN;

	// 144MHz / ((23999 + 1) * (99 + 1)) = 60Hz
	TIM10->ARR = 23999;
	TIM10->PSC = 99;

	// update shadow registers and clear irq pending bit
	TIM10->EGR |= TIM_EGR_UG;
	TIM10->SR &= ~TIM_SR_UIF;

	tim10_t1 = GetTimestamp();

	NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);

	TIM10->DIER = 1; // UPDATE IRQ ENABLE AND CC IRQ DISABLE
}

void Timer_start()
{
	SET_FIELD_32(TIM10->CR1, TIM_CR1_CEN_Msk, TIM_CR1_CEN_Pos, 1);
}

void IRQ_DMA2_SPI1_TX_Init(void)
{
	NVIC_EnableIRQ(DMA2_Stream3_IRQn);
}

void DMA2_SPI1_TX_Init(void)
{
    // 1. Włączenie zegara dla DMA2
    RCC->AHB1ENR |= RCC_AHB1ENR_DMA2EN;

    // Upewniamy się, że strumień jest wyłączony przed konfiguracją
    DMA2_Stream3->CR &= ~DMA_SxCR_EN;
    while (DMA2_Stream3->CR & DMA_SxCR_EN); // Czekaj aż faktycznie się wyłączy

    // 2. Czyszczenie rejestru konfiguracyjnego (CR) i reset flag błędów/transferu
    DMA2_Stream3->CR = 0;
    DMA2->LIFCR = DMA_LIFCR_CTCIF3 | DMA_LIFCR_CHTIF3 | DMA_LIFCR_CTEIF3 | DMA_LIFCR_CDMEIF3 | DMA_LIFCR_CFEIF3;

    // 3. Konfiguracja parametrów strumienia w rejestrze CR:
    // - Wybór Kanału 3 (CHSEL = 011b -> shift o 25)
    DMA2_Stream3->CR |= (3U << DMA_SxCR_CHSEL_Pos);

    // - Priorytet bardzo wysoki (PL = 11b -> shift o 16)
    DMA2_Stream3->CR |= (3U << DMA_SxCR_PL_Pos);

    // - Rozmiar danych pamięci (MSIZE) = 8-bit (00b)
    // - Rozmiar danych peryferium (PSIZE) = 8-bit (00b)
    DMA2_Stream3->CR &= ~(DMA_SxCR_MSIZE | DMA_SxCR_PSIZE);

    // - Inkrementacja pamięci włączona (MINC = 1)
    DMA2_Stream3->CR |= DMA_SxCR_MINC;

    // - Inkrementacja peryferium wyłączona (PINC = 0) - domyślnie czysta

    // - Kierunek: Pamięć do Peryferium (DIR = 01b -> shift o 6)
    DMA2_Stream3->CR |= (1U << DMA_SxCR_DIR_Pos);

    // 4. Konfiguracja adresów stałych
    // Adres docelowy to rejestr danych SPI1
    DMA2_Stream3->PAR = (uint32_t)&(SPI1->DR);

    // 5. Włączenie żądania DMA ze strony SPI1 (SPI TX DMA Enable)
    SPI1->CR2 |= SPI_CR2_TXDMAEN;

    // 6. Włącz przerwanie od zakończenia transferu
    DMA2_Stream3->CR |= DMA_SxCR_TCIE;
}

void GPIO_init()
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; // GPIOA clock enable
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN; // GPIOA clock enable
	RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;

	//////////////////////////////////
	// LCD_RESET
	// PA0 pull-up output
	GPIOA->BSRR = GPIO_BSRR_BS0; // init as high
//	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD2_Msk, GPIO_PUPDR_PUPD2_Pos, LL_GPIO_PULL_UP); //pull-up
//	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT2_Msk, GPIO_OTYPER_OT2_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER0_Msk, GPIO_MODER_MODER0_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// LCD_DC
	// PA1 pull-up output
	GPIOA->BSRR = GPIO_BSRR_BR1; // init as low
//	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD3_Msk, GPIO_PUPDR_PUPD3_Pos, LL_GPIO_PULL_UP); //pull-up
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED1_Msk, GPIO_OSPEEDR_OSPEED1_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
//	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT3_Msk, GPIO_OTYPER_OT3_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER1_Msk, GPIO_MODER_MODER1_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// LCD_CS
	// PA4 pull-up output
	GPIOA->BSRR = GPIO_BSRR_BS4; // init as high
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD4_Msk, GPIO_PUPDR_PUPD4_Pos, LL_GPIO_PULL_UP); //pull-up
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED4_Msk, GPIO_OSPEEDR_OSPEED4_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT4_Msk, GPIO_OTYPER_OT4_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER4_Msk, GPIO_MODER_MODER4_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// PAD_CLK
	// PA10 pull-up output
	GPIOA->BSRR = GPIO_BSRR_BR10; // init as low
//	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD3_Msk, GPIO_PUPDR_PUPD3_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED10_Msk, GPIO_OSPEEDR_OSPEED10_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
//	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT3_Msk, GPIO_OTYPER_OT3_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER10_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// PAD_LATCH
	// PB5 pull-up output
	GPIOB->BSRR = GPIO_BSRR_BR5; // init as low
//	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD5_Msk, GPIO_PUPDR_PUPD5_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED5_Msk, GPIO_OSPEEDR_OSPEED5_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
//	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT5_Msk, GPIO_OTYPER_OT5_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER5_Msk, GPIO_MODER_MODER5_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// PAD_DATA
	// PB10 pull-up input
	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD10_Msk, GPIO_PUPDR_PUPD10_Pos, LL_GPIO_PULL_UP); //pull-up
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED10_Msk, GPIO_OSPEEDR_OSPEED10_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT10_Msk, GPIO_OTYPER_OT10_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER10_Pos, LL_GPIO_MODE_INPUT); //input

	/////////////////////////////////
	// LCD_SCK
	// PA5 AF SPI1_SCK
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD5_Msk, GPIO_PUPDR_PUPD5_Pos, LL_GPIO_PULL_DOWN); //pull-dow
	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT5_Msk, GPIO_OTYPER_OT5_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED5_Msk, GPIO_OSPEEDR_OSPEED5_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
	SET_FIELD_32(GPIOA->AFR[0], GPIO_AFRL_AFSEL5_Msk, GPIO_AFRL_AFSEL5_Pos, LL_GPIO_AF_5); //AF5 - SPI1_SCK
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER5_Msk, GPIO_MODER_MODER5_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// LCD_MISO
	// PA6 AF SPI1_MISO
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD6_Msk, GPIO_PUPDR_PUPD6_Pos, LL_GPIO_PULL_NO); //pull-down
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED6_Msk, GPIO_OSPEEDR_OSPEED6_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
	SET_FIELD_32(GPIOA->AFR[0], GPIO_AFRL_AFSEL6_Msk, GPIO_AFRL_AFSEL6_Pos, LL_GPIO_AF_5); //AF5 - SPI1_MISO
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER6_Msk, GPIO_MODER_MODER6_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// LCD_MOSI
	// PA7 AF SPI1_MOSI
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD7_Msk, GPIO_PUPDR_PUPD7_Pos, LL_GPIO_PULL_NO); //pull-down
	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT7_Msk, GPIO_OTYPER_OT7_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED7_Msk, GPIO_OSPEEDR_OSPEED7_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
	SET_FIELD_32(GPIOA->AFR[0], GPIO_AFRL_AFSEL7_Msk, GPIO_AFRL_AFSEL7_Pos, LL_GPIO_AF_5); //AF5 - SPI1_MOSI
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER7_Msk, GPIO_MODER_MODER7_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// LCD_SPI CONFIG
	SET_FIELD_32(SPI1->CR1, SPI_CR1_BIDIMODE_Msk, SPI_CR1_BIDIMODE_Pos, 0); // full duplex
	SET_FIELD_32(SPI1->CR1, SPI_CR1_DFF_Msk, SPI_CR1_DFF_Pos, 0); // 8-bit data transfer
	SET_FIELD_32(SPI1->CR1, SPI_CR1_SSM_Msk, SPI_CR1_SSM_Pos, 1); // manual CS
	SET_FIELD_32(SPI1->CR1, SPI_CR1_SSI_Msk, SPI_CR1_SSI_Pos, 1); // internal NSS pull to master
	SET_FIELD_32(SPI1->CR1, SPI_CR1_BR_Msk, SPI_CR1_BR_Pos, 0b000); // APB2 clock div 128
	SET_FIELD_32(SPI1->CR1, SPI_CR1_MSTR_Msk, SPI_CR1_MSTR_Pos, 1); // spi master mode
	SET_FIELD_32(SPI1->CR1, SPI_CR1_CPOL_Msk, SPI_CR1_CPOL_Pos, 0); // SCK line low in idle
	SET_FIELD_32(SPI1->CR1, SPI_CR1_CPHA_Msk, SPI_CR1_CPHA_Pos, 0); // SCK phase 1 edge
	SET_FIELD_32(SPI1->CR1, SPI_CR1_SPE_Msk, SPI_CR1_SPE_Pos, 1); // SPI1 enable
}

void Flash_init()
{
	FLASH->ACR |= FLASH_ACR_ICEN; //instruction cache enable
	FLASH->ACR |= FLASH_ACR_DCEN; //data cache enable
	FLASH->ACR |= FLASH_ACR_PRFTEN; //prefetch enable

#if SYSCLOCK_MHZ == SYSCLOCK_144MHZ
	FLASH->ACR |= FLASH_ACR_LATENCY_4WS; //4 cycles latency
#endif

	while ((FLASH->ACR & FLASH_ACR_ICEN) != FLASH_ACR_ICEN);
	while ((FLASH->ACR & FLASH_ACR_DCEN) != FLASH_ACR_DCEN);
	while ((FLASH->ACR & FLASH_ACR_PRFTEN) != FLASH_ACR_PRFTEN);

#if SYSCLOCK_MHZ == SYSCLOCK_144MHZ
	while ((FLASH->ACR & FLASH_ACR_LATENCY_4WS) != FLASH_ACR_LATENCY_4WS);
#endif
}

void Clock_init()
{
	RCC->CR |= RCC_CR_HSION; //turn HSI on (usually always on)
	while(!(RCC->CR & RCC_CR_HSIRDY)); //wait until HSI ready

#if SYSCLOCK_MHZ == SYSCLOCK_144MHZ
	// Konfiguracja magistral (Preskalery)
	RCC->CFGR |= RCC_CFGR_HPRE_DIV1;  // AHB  = 144 MHz
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV2; // APB2 = 72 MHz
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV4; // APB1 = 36 MHz

	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSI; //HSI as PLL source

	// clk = src * (N / M) / P
	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLN_Msk; //clear PLLN prescaler
	RCC->PLLCFGR |= (144 << RCC_PLLCFGR_PLLN_Pos); //set PLLN prescaler

	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLM_Msk; //clear PLLM prescaler
	RCC->PLLCFGR |= (8 << RCC_PLLCFGR_PLLM_Pos); //set PLLM prescaler

	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLP_Msk; //clear PLLP prescaler
	RCC->PLLCFGR |= (0 << RCC_PLLCFGR_PLLP_Pos); //set PLLP prescaler

	RCC->CR |= RCC_CR_PLLON; //turn on PLL
	while ((RCC->CR & RCC_CR_PLLRDY) != RCC_CR_PLLRDY); //wait for PLL stabilization

	RCC->CFGR |= RCC_CFGR_SW_PLL; //set sysclk source as PLL
	while ((RCC->CFGR & RCC_CFGR_SWS_PLL) != RCC_CFGR_SWS_PLL); //wait for sysclk to react to change
#endif
}

void Delay_init()
{
	CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;

	DWT->CYCCNT = 0;

	DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}

void GameLoop()
{
	uint32_t buttons_state = 0;
	buttons_state = GetButtonsState();
	PrintButtons(buttons_state);

	Mario_ReactToButton(pMario, buttons_state);

	Map_ReactToButtons(pMap, buttons_state);
}

volatile bool startRender = false;

void TIM1_UP_TIM10_IRQHandler(void)
{
    if (TIM10->SR & TIM_SR_UIF_Msk)
    {
    	SET_FIELD_32(TIM10->SR, TIM_SR_UIF_Msk, TIM_SR_UIF_Pos, 0);

//    	uint32_t tdiff = CalcTimeUS(tim10_t1);
//    	tim10_t1 = GetTimestamp();
//    	printf_v("\ntdiff: %d\n", tdiff);

    	GameLoop();

    	startRender = true;
    }
}

void print_start()
{
 	printf_v("Welcome!\n");
}

int main(void)
{
	Flash_init();
	Clock_init();
	FPU_init();
	Delay_init();
	GPIO_init();
	IRQ_DMA2_SPI1_TX_Init();
	DMA2_SPI1_TX_Init();
	Timer_init();
	printf_init();

	print_start();

	RE_Init();

	LCD_init();

	Mario_Init(pMario);
	Map_Init(pMap);
	Enemies_Init(pEnemies);

	uint32_t startTime = 0, elapsedUS = 0;
	uint32_t startTime2 = 0;

	Map_FirstRender(pMap);

	Timer_start();

	while(1)
	{
		startTime = GetTimestamp();

		while(!startRender);
		startRender = false;

		startTime2 = GetTimestamp();
		Map_ScrollRender(pMap);
		elapsedUS = CalcTimeUS(startTime2);
		if (elapsedUS > 0)
		{
//			printf_uint(elapsedUS); printf_c('\t');
		}

		startTime2 = GetTimestamp();
		Map_RenderObjects(pMap);
		elapsedUS = CalcTimeUS(startTime2);
		if (elapsedUS > 0)
		{
			printf_uint(elapsedUS); printf_c('\n');
		}

//		Mario_Render(pMario);

		elapsedUS = CalcTimeUS(startTime);
		int sleepTimeUS = 16000 - (int)elapsedUS;
		if (sleepTimeUS > 0)
		{
			delayUS(sleepTimeUS);
		}
	}

    /* Loop forever */
	for(;;);
}
