/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include "stm32f4xx_ll_gpio.h"
// #include "stm32f4xx_ll_spi.h"
#include "stm32f446xx.h"
// #include "cmsis_gcc.h"

#include "NES_Defs.h"
#include "NES_Functions.h"
#include "printf_logger.h"
// #include "TimeoutTracker.h"

#include "LCDControl.h"
// #include "PADControl.h"
#include "RenderEngine.h"
#include "Sound.h"

#include "Game.h"

#define DEFINE_NES_ENGINE
#include "NESEngine.h"




void FPU_init()
{
	SCB->CPACR |= (0xF << 20);
}

volatile uint32_t tim10_t1 = 0;

void Timer_10_init()
{
	RCC->APB2ENR |= RCC_APB2ENR_TIM10EN;

	// 144MHz / ((23999 + 1) * (99 + 1)) = 60Hz
	TIM10->ARR = 23999;
	TIM10->PSC = 99;

	// update shadow registers and clear irq pending bit
	TIM10->EGR |= TIM_EGR_UG;
	TIM10->SR &= ~TIM_SR_UIF;

	tim10_t1 = GetTimestamp();

	NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);

	TIM10->DIER = 1; // UPDATE IRQ ENABLE AND CC IRQ DISABLE
}

void Timer_10_start()
{
	SET_FIELD_32(TIM10->CR1, TIM_CR1_CEN_Msk, TIM_CR1_CEN_Pos, 1);
}

void IRQ_init(void)
{
	NVIC_SetPriorityGrouping(3); // all 4 bits are for priorities, no subgroups
}

void IRQ_DMA2_SPI1_TX_Init(void)
{
	NVIC_SetPriority(DMA2_Stream3_IRQn, 10); // not too high not too low :)
	NVIC_EnableIRQ(DMA2_Stream3_IRQn);
}

void DMA2_SPI1_TX_Init(void)
{
    // 1. Włączenie zegara dla DMA2
    RCC->AHB1ENR |= RCC_AHB1ENR_DMA2EN;

    // Upewniamy się, że strumień jest wyłączony przed konfiguracją
    DMA2_Stream3->CR &= ~DMA_SxCR_EN;
    while (DMA2_Stream3->CR & DMA_SxCR_EN); // Czekaj aż faktycznie się wyłączy

    // 2. Czyszczenie rejestru konfiguracyjnego (CR) i reset flag błędów/transferu
    DMA2_Stream3->CR = 0;
    DMA2->LIFCR = DMA_LIFCR_CTCIF3 | DMA_LIFCR_CHTIF3 | DMA_LIFCR_CTEIF3 | DMA_LIFCR_CDMEIF3 | DMA_LIFCR_CFEIF3;

    // 3. Konfiguracja parametrów strumienia w rejestrze CR:
    // - Wybór Kanału 3 (CHSEL = 011b -> shift o 25)
    DMA2_Stream3->CR |= (3U << DMA_SxCR_CHSEL_Pos);

    // - Priorytet wysoki (PL = 10b -> shift o 16)
    DMA2_Stream3->CR |= (2U << DMA_SxCR_PL_Pos);

    // - Rozmiar danych pamięci (MSIZE) = 8-bit (00b)
    // - Rozmiar danych peryferium (PSIZE) = 8-bit (00b)
    DMA2_Stream3->CR &= ~(DMA_SxCR_MSIZE | DMA_SxCR_PSIZE);

    // - Inkrementacja pamięci włączona (MINC = 1)
    DMA2_Stream3->CR |= DMA_SxCR_MINC;

    // - Inkrementacja peryferium wyłączona (PINC = 0) - domyślnie czysta

    // - Kierunek: Pamięć do Peryferium (DIR = 01b -> shift o 6)
    DMA2_Stream3->CR |= (1U << DMA_SxCR_DIR_Pos);

    // 4. Konfiguracja adresów stałych
    // Adres docelowy to rejestr danych SPI1
    DMA2_Stream3->PAR = (uint32_t)&(SPI1->DR);

    // 5. Włączenie żądania DMA ze strony SPI1 (SPI TX DMA Enable)
    SPI1->CR2 |= SPI_CR2_TXDMAEN;

    // 6. Włącz przerwanie od zakończenia transferu
    DMA2_Stream3->CR |= DMA_SxCR_TCIE;
}

void GPIO_LCD_PAD_init()
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; // GPIOA clock enable
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN; // GPIOB clock enable
	RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;  // SPI1 clock enable

	//////////////////////////////////
	// LCD_RESET
	// PA0 pull-up output
	GPIOA->BSRR = GPIO_BSRR_BS0; // init as high
//	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD2_Msk, GPIO_PUPDR_PUPD2_Pos, LL_GPIO_PULL_UP); //pull-up
//	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT2_Msk, GPIO_OTYPER_OT2_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER0_Msk, GPIO_MODER_MODER0_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// LCD_DC
	// PA1 pull-up output
	GPIOA->BSRR = GPIO_BSRR_BR1; // init as low
//	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD3_Msk, GPIO_PUPDR_PUPD3_Pos, LL_GPIO_PULL_UP); //pull-up
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED1_Msk, GPIO_OSPEEDR_OSPEED1_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
//	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT3_Msk, GPIO_OTYPER_OT3_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER1_Msk, GPIO_MODER_MODER1_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// LCD_CS
	// PA4 pull-up output
	GPIOA->BSRR = GPIO_BSRR_BS4; // init as high
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD4_Msk, GPIO_PUPDR_PUPD4_Pos, LL_GPIO_PULL_UP); //pull-up
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED4_Msk, GPIO_OSPEEDR_OSPEED4_Pos, LL_GPIO_SPEED_FREQ_VERY_HIGH); //fast speed
	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT4_Msk, GPIO_OTYPER_OT4_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER4_Msk, GPIO_MODER_MODER4_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// PAD_CLK
	// PA10 pull-up output
	GPIOA->BSRR = GPIO_BSRR_BR10; // init as low
//	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD3_Msk, GPIO_PUPDR_PUPD3_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED10_Msk, GPIO_OSPEEDR_OSPEED10_Pos, LL_GPIO_SPEED_FREQ_LOW); //low speed
//	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT3_Msk, GPIO_OTYPER_OT3_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER10_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// PAD_LATCH
	// PB5 pull-up output
	GPIOB->BSRR = GPIO_BSRR_BR5; // init as low
//	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD5_Msk, GPIO_PUPDR_PUPD5_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED5_Msk, GPIO_OSPEEDR_OSPEED5_Pos, LL_GPIO_SPEED_FREQ_LOW); //low speed
//	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT5_Msk, GPIO_OTYPER_OT5_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER5_Msk, GPIO_MODER_MODER5_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// PAD_DATA
	// PB10 pull-up input
	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD10_Msk, GPIO_PUPDR_PUPD10_Pos, LL_GPIO_PULL_UP); //pull-up
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED10_Msk, GPIO_OSPEEDR_OSPEED10_Pos, LL_GPIO_SPEED_FREQ_LOW); //low speed
	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT10_Msk, GPIO_OTYPER_OT10_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER10_Pos, LL_GPIO_MODE_INPUT); //input

	/////////////////////////////////
	// LCD_SCK
	// PA5 AF SPI1_SCK
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD5_Msk, GPIO_PUPDR_PUPD5_Pos, LL_GPIO_PULL_DOWN); //pull-dow
	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT5_Msk, GPIO_OTYPER_OT5_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED5_Msk, GPIO_OSPEEDR_OSPEED5_Pos, LL_GPIO_SPEED_FREQ_HIGH); //fast speed
	SET_FIELD_32(GPIOA->AFR[0], GPIO_AFRL_AFSEL5_Msk, GPIO_AFRL_AFSEL5_Pos, LL_GPIO_AF_5); //AF5 - SPI1_SCK
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER5_Msk, GPIO_MODER_MODER5_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// LCD_MISO
	// PA6 AF SPI1_MISO
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD6_Msk, GPIO_PUPDR_PUPD6_Pos, LL_GPIO_PULL_NO); //pull-down
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED6_Msk, GPIO_OSPEEDR_OSPEED6_Pos, LL_GPIO_SPEED_FREQ_HIGH); //fast speed
	SET_FIELD_32(GPIOA->AFR[0], GPIO_AFRL_AFSEL6_Msk, GPIO_AFRL_AFSEL6_Pos, LL_GPIO_AF_5); //AF5 - SPI1_MISO
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER6_Msk, GPIO_MODER_MODER6_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// LCD_MOSI
	// PA7 AF SPI1_MOSI
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD7_Msk, GPIO_PUPDR_PUPD7_Pos, LL_GPIO_PULL_NO); //pull-down
	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT7_Msk, GPIO_OTYPER_OT7_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED7_Msk, GPIO_OSPEEDR_OSPEED7_Pos, LL_GPIO_SPEED_FREQ_HIGH); //fast speed
	SET_FIELD_32(GPIOA->AFR[0], GPIO_AFRL_AFSEL7_Msk, GPIO_AFRL_AFSEL7_Pos, LL_GPIO_AF_5); //AF5 - SPI1_MOSI
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER7_Msk, GPIO_MODER_MODER7_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// LCD_SPI CONFIG
	SET_FIELD_32(SPI1->CR1, SPI_CR1_BIDIMODE_Msk, SPI_CR1_BIDIMODE_Pos, 0); // full duplex
	SET_FIELD_32(SPI1->CR1, SPI_CR1_DFF_Msk, SPI_CR1_DFF_Pos, 0); // 8-bit data transfer
	SET_FIELD_32(SPI1->CR1, SPI_CR1_SSM_Msk, SPI_CR1_SSM_Pos, 1); // manual CS
	SET_FIELD_32(SPI1->CR1, SPI_CR1_SSI_Msk, SPI_CR1_SSI_Pos, 1); // internal NSS pull to master
	SET_FIELD_32(SPI1->CR1, SPI_CR1_BR_Msk, SPI_CR1_BR_Pos, 0b000); // APB2 clock div 128
	SET_FIELD_32(SPI1->CR1, SPI_CR1_MSTR_Msk, SPI_CR1_MSTR_Pos, 1); // spi master mode
	SET_FIELD_32(SPI1->CR1, SPI_CR1_CPOL_Msk, SPI_CR1_CPOL_Pos, 0); // SCK line low in idle
	SET_FIELD_32(SPI1->CR1, SPI_CR1_CPHA_Msk, SPI_CR1_CPHA_Pos, 0); // SCK phase 1 edge
	SET_FIELD_32(SPI1->CR1, SPI_CR1_SPE_Msk, SPI_CR1_SPE_Pos, 1); // SPI1 enable
}

void Flash_init()
{
	FLASH->ACR |= FLASH_ACR_ICEN; //instruction cache enable
	FLASH->ACR |= FLASH_ACR_DCEN; //data cache enable
	FLASH->ACR |= FLASH_ACR_PRFTEN; //prefetch enable

#if SYSCLOCK_MHZ == SYSCLOCK_144MHZ
	FLASH->ACR |= FLASH_ACR_LATENCY_4WS; //4 cycles latency
#endif

	while ((FLASH->ACR & FLASH_ACR_ICEN) != FLASH_ACR_ICEN);
	while ((FLASH->ACR & FLASH_ACR_DCEN) != FLASH_ACR_DCEN);
	while ((FLASH->ACR & FLASH_ACR_PRFTEN) != FLASH_ACR_PRFTEN);

#if SYSCLOCK_MHZ == SYSCLOCK_144MHZ
	while ((FLASH->ACR & FLASH_ACR_LATENCY_4WS) != FLASH_ACR_LATENCY_4WS);
#endif
}

void Clock_init()
{
	RCC->CR |= RCC_CR_HSION; //turn HSI on (usually always on)
	while(!(RCC->CR & RCC_CR_HSIRDY)); //wait until HSI ready

#if SYSCLOCK_MHZ == SYSCLOCK_144MHZ
	// Konfiguracja magistral (Preskalery)
	RCC->CFGR |= RCC_CFGR_HPRE_DIV1;  // AHB  = 144 MHz
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV2; // APB2 = 72 MHz
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV4; // APB1 = 36 MHz

	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSI; //HSI as PLL source

	// clk = src * (N / M) / P
	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLN_Msk; //clear PLLN prescaler
	RCC->PLLCFGR |= (144 << RCC_PLLCFGR_PLLN_Pos); //set PLLN prescaler

	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLM_Msk; //clear PLLM prescaler
	RCC->PLLCFGR |= (8 << RCC_PLLCFGR_PLLM_Pos); //set PLLM prescaler

	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLP_Msk; //clear PLLP prescaler
	RCC->PLLCFGR |= (0 << RCC_PLLCFGR_PLLP_Pos); //set PLLP prescaler

	RCC->CR |= RCC_CR_PLLON; //turn on PLL
	while ((RCC->CR & RCC_CR_PLLRDY) != RCC_CR_PLLRDY); //wait for PLL stabilization

	RCC->CFGR |= RCC_CFGR_SW_PLL; //set sysclk source as PLL
	while ((RCC->CFGR & RCC_CFGR_SWS_PLL) != RCC_CFGR_SWS_PLL); //wait for sysclk to react to change
#endif
}

void Delay_init()
{
	CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;

	DWT->CYCCNT = 0;

	DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}

volatile bool startRender = false;

void TIM1_UP_TIM10_IRQHandler(void)
{
    if (TIM10->SR & TIM_SR_UIF_Msk)
    {
    	SET_FIELD_32(TIM10->SR, TIM_SR_UIF_Msk, TIM_SR_UIF_Pos, 0);

//    	uint32_t tdiff = CalcTimeUS(tim10_t1);
//    	tim10_t1 = GetTimestamp();
//    	printf_v("\ntdiff: %d\n", tdiff);

    	startRender = true;
    }
}

#if I2S_SOUND == I2S_2

void IRQ_DMA1_I2S2_TX_Init(void)
{
	NVIC_SetPriority(DMA1_Stream4_IRQn, 5); //absolutely critical! highest prio available
	NVIC_EnableIRQ(DMA1_Stream4_IRQn);
}

void DMA1_I2S2_TX_init(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_DMA1EN; // DMA1 clock enable

	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_EN_Msk, DMA_SxCR_EN_Pos, 0); // stream disable
	while ((DMA1_Stream4->CR & DMA_SxCR_EN_Msk) == 1); // wait until disabled

	// clear all interrupt flag registers
	DMA1_Stream4->CR = 0;
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CTCIF4_Msk, DMA_HIFCR_CTCIF4_Pos, 1);
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CHTIF4_Msk, DMA_HIFCR_CHTIF4_Pos, 1);
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CTEIF4_Msk, DMA_HIFCR_CTEIF4_Pos, 1);
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CDMEIF4_Msk, DMA_HIFCR_CDMEIF4_Pos, 1);
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CFEIF4_Msk, DMA_HIFCR_CFEIF4_Pos, 1);

	DMA1_Stream4->PAR = (uint32_t)&SPI2->DR; // peripheral address
	int16_t* memPtr = SOUND_GetBufferPtr();
	if (memPtr != NULL) {
		DMA1_Stream4->M0AR = (uint32_t)memPtr; // memory address
	} else {
		return;
	}
	DMA1_Stream4->NDTR = SOUND_BUFFER_SIZE; // buffer size

	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_CHSEL_Msk, DMA_SxCR_CHSEL_Pos, 0b000); // channel 0
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_PFCTRL_Msk, DMA_SxCR_PFCTRL_Pos, 0); // dma is flow controller
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_PL_Msk, DMA_SxCR_PL_Pos, 0b11); // very high priority
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_MSIZE_Msk, DMA_SxCR_MSIZE_Pos, 0b01); // 16-bit memory data size
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_PSIZE_Msk, DMA_SxCR_PSIZE_Pos, 0b01); // 16-bit peripheral data size
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_MINC_Msk, DMA_SxCR_MINC_Pos, 1); // memory increment mode
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_DIR_Msk, DMA_SxCR_DIR_Pos, 0b01); // memory to peripheral
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_CIRC_Msk, DMA_SxCR_CIRC_Pos, 1); // circular mode
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_TCIE_Msk, DMA_SxCR_TCIE_Pos, 1); // transfer complete interrupt enable
	SET_FIELD_32(DMA1_Stream4->CR, DMA_SxCR_HTIE_Msk, DMA_SxCR_HTIE_Pos, 1); // half transfer complete interrupt enable

	SET_FIELD_32(DMA1_Stream4->FCR, DMA_SxFCR_DMDIS_Msk, DMA_SxFCR_DMDIS_Pos, 1); // direct mode disable (fifo enable)
	SET_FIELD_32(DMA1_Stream4->FCR, DMA_SxFCR_FTH_Msk, DMA_SxFCR_FTH_Pos, 0b11); // full fifo threshold
}

void I2S_init(void)
{
	// I2S APB1 clock source selection
	// I2S1 here means I2S interfaces on APB1
	SET_FIELD_32(RCC->DCKCFGR, RCC_DCKCFGR_I2S1SRC_Msk, RCC_DCKCFGR_I2S1SRC_Pos, 0b11); // HSE or HSI
	RCC->APB1ENR |= RCC_APB1ENR_SPI2EN; // I2S2 clock enable

	/////////////////////////////////
	// SPK_SDMODE
	// PB14 pull-down output
	GPIOB->BSRR = GPIO_BSRR_BR14; // init as low
	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD14_Msk, GPIO_PUPDR_PUPD14_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED14_Msk, GPIO_OSPEEDR_OSPEED14_Pos, LL_GPIO_SPEED_FREQ_LOW); //low speed
	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT14_Msk, GPIO_OTYPER_OT14_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER14_Msk, GPIO_MODER_MODER14_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// SPK_SD
	// PB15 AF5 I2S2_SD
	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD15_Msk, GPIO_PUPDR_PUPD15_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT15_Msk, GPIO_OTYPER_OT15_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED15_Msk, GPIO_OSPEEDR_OSPEED15_Pos, LL_GPIO_SPEED_FREQ_MEDIUM); //medium speed
	SET_FIELD_32(GPIOB->AFR[1], GPIO_AFRH_AFSEL15_Msk, GPIO_AFRH_AFSEL15_Pos, LL_GPIO_AF_5); //AF5 - I2S2_SD
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER15_Msk, GPIO_MODER_MODER15_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// SPK_CK
	// PB13 AF5 I2S2_CK
	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD13_Msk, GPIO_PUPDR_PUPD13_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT13_Msk, GPIO_OTYPER_OT13_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED13_Msk, GPIO_OSPEEDR_OSPEED13_Pos, LL_GPIO_SPEED_FREQ_MEDIUM); //medium speed
	SET_FIELD_32(GPIOB->AFR[1], GPIO_AFRH_AFSEL13_Msk, GPIO_AFRH_AFSEL13_Pos, LL_GPIO_AF_5); //AF5 - I2S2_CK
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER13_Msk, GPIO_MODER_MODER13_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function
//	SET_FIELD_32(GPIOC->PUPDR, GPIO_PUPDR_PUPD7_Msk, GPIO_PUPDR_PUPD7_Pos, LL_GPIO_PULL_DOWN); //pull-down
//	SET_FIELD_32(GPIOC->OTYPER, GPIO_OTYPER_OT7_Msk, GPIO_OTYPER_OT7_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
//	SET_FIELD_32(GPIOC->OSPEEDR, GPIO_OSPEEDR_OSPEED7_Msk, GPIO_OSPEEDR_OSPEED7_Pos, LL_GPIO_SPEED_FREQ_MEDIUM); //medium speed
//	SET_FIELD_32(GPIOC->AFR[0], GPIO_AFRL_AFSEL7_Msk, GPIO_AFRL_AFSEL7_Pos, LL_GPIO_AF_5); //AF5 - I2S2_CK
//	SET_FIELD_32(GPIOC->MODER, GPIO_MODER_MODER7_Msk, GPIO_MODER_MODER7_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// SPK_WS
	// PB12 AF5 I2S2_WS
//	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD12_Msk, GPIO_PUPDR_PUPD12_Pos, LL_GPIO_PULL_DOWN); //pull-down
//	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT12_Msk, GPIO_OTYPER_OT12_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
//	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED12_Msk, GPIO_OSPEEDR_OSPEED12_Pos, LL_GPIO_SPEED_FREQ_MEDIUM); //medium speed
//	SET_FIELD_32(GPIOB->AFR[1], GPIO_AFRH_AFSEL12_Msk, GPIO_AFRH_AFSEL12_Pos, LL_GPIO_AF_5); //AF5 - I2S2_WS
//	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER12_Msk, GPIO_MODER_MODER12_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function
	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD4_Msk, GPIO_PUPDR_PUPD4_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT4_Msk, GPIO_OTYPER_OT4_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED4_Msk, GPIO_OSPEEDR_OSPEED4_Pos, LL_GPIO_SPEED_FREQ_MEDIUM); //medium speed
	SET_FIELD_32(GPIOB->AFR[0], GPIO_AFRL_AFSEL4_Msk, GPIO_AFRL_AFSEL4_Pos, LL_GPIO_AF_7); //AF7 - I2S2_WS
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER4_Msk, GPIO_MODER_MODER4_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	SET_FIELD_32(SPI2->I2SCFGR, SPI_I2SCFGR_I2SMOD_Msk, SPI_I2SCFGR_I2SMOD_Pos, 1); // I2S mode instead of default SPI mode

	// HSI 16MHz -> sample rate 16KHz
	SET_FIELD_32(SPI2->I2SPR, SPI_I2SPR_I2SDIV_Msk, SPI_I2SPR_I2SDIV_Pos, 15);
	SET_FIELD_32(SPI2->I2SPR, SPI_I2SPR_ODD_Msk, SPI_I2SPR_ODD_Pos, 1);

	SET_FIELD_32(SPI2->I2SCFGR, SPI_I2SCFGR_CKPOL_Msk, SPI_I2SCFGR_CKPOL_Pos, 1); // I2S clock steady state is high level
	SET_FIELD_32(SPI2->I2SCFGR, SPI_I2SCFGR_I2SCFG_Msk, SPI_I2SCFGR_I2SCFG_Pos, 0b10); // Master - transmit
	SET_FIELD_32(SPI2->I2SCFGR, SPI_I2SCFGR_I2SSTD_Msk, SPI_I2SCFGR_I2SSTD_Pos, 0); // I2S Phillips standard

	SET_FIELD_32(SPI2->I2SCFGR, SPI_I2SCFGR_DATLEN_Msk, SPI_I2SCFGR_DATLEN_Pos, 0); // 16-bit data length
	SET_FIELD_32(SPI2->I2SCFGR, SPI_I2SCFGR_CHLEN_Msk, SPI_I2SCFGR_CHLEN_Pos, 0); // 16-bit wide

	SET_FIELD_32(SPI2->CR2, SPI_CR2_TXDMAEN_Msk, SPI_CR2_TXDMAEN_Pos, 1); // Tx buffer DMA enable

	SET_FIELD_32(SPI2->I2SCFGR, SPI_I2SCFGR_I2SE_Msk, SPI_I2SCFGR_I2SE_Pos, 1); // I2S2 enable
}

void I2S_Start(void)
{
	// Switch ON MAX98357A
	GPIOB->BSRR = GPIO_BSRR_BS14;
	delay(1);
	//Start DMA
	DMA1_Stream4->CR |= DMA_SxCR_EN;
}

#elif I2S_SOUND == I2S_3

void IRQ_DMA1_I2S3_TX_Init(void)
{
	NVIC_SetPriority(DMA1_Stream7_IRQn, 1); //absolutely critical! highest prio available
	NVIC_EnableIRQ(DMA1_Stream7_IRQn);
}

void I2S_init(void)
{
	// I2S APB1 clock source selection
	// I2S1 here means I2S interfaces on APB1
	SET_FIELD_32(RCC->DCKCFGR, RCC_DCKCFGR_I2S1SRC_Msk, RCC_DCKCFGR_I2S1SRC_Pos, 0b11); // HSE or HSI
	RCC->APB1ENR |= RCC_APB1ENR_SPI3EN; // I2S3 clock enable
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN; // GPIOC clock enable

	/////////////////////////////////
	// SPK_SDMODE
	// PB7 pull-down output
	GPIOB->BSRR = GPIO_BSRR_BR7; // init as low
	SET_FIELD_32(GPIOB->PUPDR, GPIO_PUPDR_PUPD7_Msk, GPIO_PUPDR_PUPD7_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEED7_Msk, GPIO_OSPEEDR_OSPEED7_Pos, LL_GPIO_SPEED_FREQ_LOW); //low speed
	SET_FIELD_32(GPIOB->OTYPER, GPIO_OTYPER_OT7_Msk, GPIO_OTYPER_OT7_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOB->MODER, GPIO_MODER_MODER7_Msk, GPIO_MODER_MODER7_Pos, LL_GPIO_MODE_OUTPUT); //output

	/////////////////////////////////
	// SPK_SD
	// PC12 AF6 I2S2_SD
	SET_FIELD_32(GPIOC->PUPDR, GPIO_PUPDR_PUPD12_Msk, GPIO_PUPDR_PUPD12_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOC->OTYPER, GPIO_OTYPER_OT12_Msk, GPIO_OTYPER_OT12_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOC->OSPEEDR, GPIO_OSPEEDR_OSPEED12_Msk, GPIO_OSPEEDR_OSPEED12_Pos, LL_GPIO_SPEED_FREQ_LOW); //low speed
	SET_FIELD_32(GPIOC->AFR[1], GPIO_AFRH_AFSEL12_Msk, GPIO_AFRH_AFSEL12_Pos, LL_GPIO_AF_6); //AF6 - I2S3_SD
	SET_FIELD_32(GPIOC->MODER, GPIO_MODER_MODER12_Msk, GPIO_MODER_MODER12_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// SPK_CK
	// PC10 AF6 I2S3_CK
	SET_FIELD_32(GPIOC->PUPDR, GPIO_PUPDR_PUPD10_Msk, GPIO_PUPDR_PUPD10_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOC->OTYPER, GPIO_OTYPER_OT10_Msk, GPIO_OTYPER_OT10_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOC->OSPEEDR, GPIO_OSPEEDR_OSPEED10_Msk, GPIO_OSPEEDR_OSPEED10_Pos, LL_GPIO_SPEED_FREQ_LOW); //low speed
	SET_FIELD_32(GPIOC->AFR[1], GPIO_AFRH_AFSEL10_Msk, GPIO_AFRH_AFSEL10_Pos, LL_GPIO_AF_6); //AF6 - I2S3_CK
	SET_FIELD_32(GPIOC->MODER, GPIO_MODER_MODER10_Msk, GPIO_MODER_MODER10_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// SPK_WS
	// PA15 AF6 I2S3_WS
	SET_FIELD_32(GPIOA->PUPDR, GPIO_PUPDR_PUPD15_Msk, GPIO_PUPDR_PUPD15_Pos, LL_GPIO_PULL_DOWN); //pull-down
	SET_FIELD_32(GPIOA->OTYPER, GPIO_OTYPER_OT15_Msk, GPIO_OTYPER_OT15_Pos, LL_GPIO_OUTPUT_PUSHPULL); //push-pull
	SET_FIELD_32(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEED15_Msk, GPIO_OSPEEDR_OSPEED15_Pos, LL_GPIO_SPEED_FREQ_LOW); //low speed
	SET_FIELD_32(GPIOA->AFR[1], GPIO_AFRH_AFSEL15_Msk, GPIO_AFRH_AFSEL15_Pos, LL_GPIO_AF_6); //AF6 - I2S3_WS
	SET_FIELD_32(GPIOA->MODER, GPIO_MODER_MODER15_Msk, GPIO_MODER_MODER15_Pos, LL_GPIO_MODE_ALTERNATE); //alternate function

	/////////////////////////////////
	// I2S_3
	SET_FIELD_32(SPI3->I2SCFGR, SPI_I2SCFGR_I2SMOD_Msk, SPI_I2SCFGR_I2SMOD_Pos, 1); // I2S mode instead of default SPI mode

	// HSI 16MHz -> sample rate 16KHz
	SET_FIELD_32(SPI3->I2SPR, SPI_I2SPR_I2SDIV_Msk, SPI_I2SPR_I2SDIV_Pos, 15);
	SET_FIELD_32(SPI3->I2SPR, SPI_I2SPR_ODD_Msk, SPI_I2SPR_ODD_Pos, 1);

	SET_FIELD_32(SPI3->I2SCFGR, SPI_I2SCFGR_CKPOL_Msk, SPI_I2SCFGR_CKPOL_Pos, 1); // I2S clock steady state is high level
	SET_FIELD_32(SPI3->I2SCFGR, SPI_I2SCFGR_I2SCFG_Msk, SPI_I2SCFGR_I2SCFG_Pos, 0b10); // Master - transmit
	SET_FIELD_32(SPI3->I2SCFGR, SPI_I2SCFGR_I2SSTD_Msk, SPI_I2SCFGR_I2SSTD_Pos, 0); // I2S Phillips standard

	SET_FIELD_32(SPI3->I2SCFGR, SPI_I2SCFGR_DATLEN_Msk, SPI_I2SCFGR_DATLEN_Pos, 0); // 16-bit data length
	SET_FIELD_32(SPI3->I2SCFGR, SPI_I2SCFGR_CHLEN_Msk, SPI_I2SCFGR_CHLEN_Pos, 0); // 16-bit wide

	SET_FIELD_32(SPI3->CR2, SPI_CR2_TXDMAEN_Msk, SPI_CR2_TXDMAEN_Pos, 1); // Tx buffer DMA enable

	SET_FIELD_32(SPI3->I2SCFGR, SPI_I2SCFGR_I2SE_Msk, SPI_I2SCFGR_I2SE_Pos, 1); // I2S3 enable
}

void DMA1_I2S3_TX_init(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_DMA1EN; // DMA1 clock enable

	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_EN_Msk, DMA_SxCR_EN_Pos, 0); // stream disable
	while ((DMA1_Stream7->CR & DMA_SxCR_EN_Msk) == 1); // wait until disabled

	// clear all interrupt flag registers
	DMA1_Stream7->CR = 0;
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CTCIF7_Msk, DMA_HIFCR_CTCIF7_Pos, 1);
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CHTIF7_Msk, DMA_HIFCR_CHTIF7_Pos, 1);
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CTEIF7_Msk, DMA_HIFCR_CTEIF7_Pos, 1);
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CDMEIF7_Msk, DMA_HIFCR_CDMEIF7_Pos, 1);
	SET_FIELD_32(DMA1->HIFCR, DMA_HIFCR_CFEIF7_Msk, DMA_HIFCR_CFEIF7_Pos, 1);

	DMA1_Stream7->PAR = (uint32_t)&SPI3->DR; // peripheral address
	int16_t* memPtr = SOUND_GetBufferPtr();
	if (memPtr != NULL) {
		DMA1_Stream7->M0AR = (uint32_t)memPtr; // memory address
	} else {
		return;
	}
	DMA1_Stream7->NDTR = SOUND_BUFFER_SIZE; // buffer size

	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_CHSEL_Msk, DMA_SxCR_CHSEL_Pos, 0b000); // channel 0
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_PFCTRL_Msk, DMA_SxCR_PFCTRL_Pos, 0); // dma is flow controller
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_PL_Msk, DMA_SxCR_PL_Pos, 0b11); // very high priority
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_MSIZE_Msk, DMA_SxCR_MSIZE_Pos, 0b01); // 16-bit memory data size
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_PSIZE_Msk, DMA_SxCR_PSIZE_Pos, 0b01); // 16-bit peripheral data size
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_MINC_Msk, DMA_SxCR_MINC_Pos, 1); // memory increment mode
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_DIR_Msk, DMA_SxCR_DIR_Pos, 0b01); // memory to peripheral
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_CIRC_Msk, DMA_SxCR_CIRC_Pos, 1); // circular mode
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_TCIE_Msk, DMA_SxCR_TCIE_Pos, 1); // transfer complete interrupt enable
	SET_FIELD_32(DMA1_Stream7->CR, DMA_SxCR_HTIE_Msk, DMA_SxCR_HTIE_Pos, 1); // half transfer complete interrupt enable

	SET_FIELD_32(DMA1_Stream7->FCR, DMA_SxFCR_DMDIS_Msk, DMA_SxFCR_DMDIS_Pos, 1); // direct mode disable (fifo enable)
	SET_FIELD_32(DMA1_Stream7->FCR, DMA_SxFCR_FTH_Msk, DMA_SxFCR_FTH_Pos, 0b11); // full fifo threshold
}

void I2S_Start(void)
{
	// Switch ON MAX98357A
	GPIOB->BSRR = GPIO_BSRR_BS7;
	delay(1);
	//Start DMA
	DMA1_Stream7->CR |= DMA_SxCR_EN;
}

#endif

void print_start()
{
 	printf_v("Welcome!\n");
}

#define TIMESTAMPS_SIZE		16

int main(void)
{
	Flash_init();
	Clock_init();
	FPU_init();
	IRQ_init();
	Delay_init();
	GPIO_LCD_PAD_init();
	IRQ_DMA2_SPI1_TX_Init();
	DMA2_SPI1_TX_Init();
	SOUND_Init();
	I2S_init();
#if I2S_SOUND == I2S_2
	DMA1_I2S2_TX_init();
	IRQ_DMA1_I2S2_TX_Init();
#elif I2S_SOUND == I2S_3
	DMA1_I2S3_TX_init();
	IRQ_DMA1_I2S3_TX_Init();
#endif
	Timer_10_init();
	printf_init();

	print_start();

//#ifdef TESTY_MUZYKI


//	while(1)
//	{
////	    TimeoutTracker_t timer = timeout_start_ms(100);
////		while (!(SPI2->SR & SPI_SR_TXE)) {	// Zakonczono wysylanie
////			if (timeout_has_expired(&timer)) {
////				break;
////			}
////		}
////		*(volatile int16_t *)&SPI2->DR = 0x100;
//////		printf_c('d'); printf_c('\n');
//	}
//
////	uint32_t startTime = 0, startLoop = 0;
////	uint32_t timeSpent = 0, loopTimeSpent = 0;
////
////	for (int i = 0; i < 100000000; i++)
////	{
////		startLoop = GetTimestamp();
////		for (int j = 0; j < 1; j++)
////		{
////			startTime = GetTimestamp();
////			SOUND_Irq_TEST();
////			timeSpent = GetTimestamp();
////		}
//////		loopTimeSpent = GetTimestamp();
//////		printf_v("Loop %d t0: %d, t1: %d\n", i, CalcDiffTimeUS(startTime, timeSpent), CalcDiffTimeUS(startLoop, loopTimeSpent));
////	}


//#else
	RE_Init();

	LCD_init();

	I2S_Start();

	uint32_t startTime[TIMESTAMPS_SIZE] = {0}, finishTime[TIMESTAMPS_SIZE] = {0};
	int timeStaps = 0;
	uint32_t frameNumber = 0;
	int ret = 0;

//	Timer_10_start();


	GAME_InitContext(pGameCtx);

	RENDERER_FirstRender(pGameCtx);

	u32 timeSpentInLoopUS = 0;
	u32 targetFrameTimeUS = 1000000/TARGET_FRAMERATE_HZ;


	while(1)
	{
		if (timeSpentInLoopUS < targetFrameTimeUS)
		{
			u32 timeToDelayUS = targetFrameTimeUS - timeSpentInLoopUS;
			delayUS(timeToDelayUS);
		}

		u32 startLoopTime = GetTimestamp();
		{
			timeStaps = 0;

			startTime[timeStaps] = GetTimestamp();
			ret = INPUT_Update(&pGameCtx->input, pGameCtx, targetFrameTimeUS);
			finishTime[timeStaps] = GetTimestamp();
			if (ret < 0)	{ delay(1); continue; }
			timeStaps++;

			startTime[timeStaps] = GetTimestamp();
			ret = ENEMIES_UpdateFlags(&pGameCtx->enemies, pGameCtx);
			finishTime[timeStaps] = GetTimestamp();
			if (ret < 0)	{ delay(1); continue; }
			timeStaps++;

			startTime[timeStaps] = GetTimestamp();
			ret = PHYSICS_Update(pGameCtx);
			finishTime[timeStaps] = GetTimestamp();
			if (ret < 0)	{ delay(1); continue; }
			timeStaps++;

			startTime[timeStaps] = GetTimestamp();
			ret = CAMERA_Update(&pGameCtx->camera, pGameCtx);
			finishTime[timeStaps] = GetTimestamp();
			if (ret < 0)	{ delay(1); continue; }
			timeStaps++;

			startTime[timeStaps] = GetTimestamp();
			ret = PLAYER_ClearFlags(&pGameCtx->player);
			finishTime[timeStaps] = GetTimestamp();
			if (ret < 0)	{ delay(1); continue; }
			timeStaps++;

			startTime[timeStaps] = GetTimestamp();
			ret = COLLISION_Update(pGameCtx);
			finishTime[timeStaps] = GetTimestamp();
			if (ret < 0)	{ delay(1); continue; }
			timeStaps++;

			startTime[timeStaps] = GetTimestamp();
			ret = RENDERER_Update(pGameCtx);
			finishTime[timeStaps] = GetTimestamp();
			if (ret < 0)	{ delay(1); continue; }
			timeStaps++;

			if (0)
			{
				printf_v("Frame %d time: %d us, timestamps:\n", frameNumber, CalcDiffTimeUS(startTime[0], finishTime[timeStaps-1]));
				for (int i = 0; i < timeStaps; i++)
				{
					printf_uint(CalcDiffTimeUS(startTime[i], finishTime[i]));
					printf_c('\t');
				}
				printf_c('\n');
			}

			frameNumber++;
		}
		timeSpentInLoopUS = CalcTimeUS(startLoopTime);
	}
//#endif

    /* Loop forever */
	for(;;);
}

